language: python

python:
  - "3.6"

install:
  - "pip install ."
  - "pip install -r requirements.txt"

script:
  - "cd application"
  - "pip install django"
  - "pip install djangorestframework"
  - "pip install markdown"  
  - "pip install django-filter"
  - "python manage.py test"
  - "cd .."