# Generated by Django 2.0.5 on 2018-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180428_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser',
            name='login_session',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
