# Generated by Django 2.0.5 on 2018-05-14 08:57

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20180513_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser',
            name='username_id',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
