# Generated by Django 2.0.2 on 2018-06-11 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20180606_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramstory',
            name='instagram_user',
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
