# Generated by Django 2.0.2 on 2018-05-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180428_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ScheduledImage',
        ),
    ]
