# Generated by Django 2.0.5 on 2018-05-13 15:48

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_instagramuser_login_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='login_session',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
