# Generated by Django 2.0.5 on 2018-05-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180513_0202'),
        ('database', '0005_instagramuser_username_id'),
    ]

    operations = [
    ]
