# Generated by Django 2.0.2 on 2018-06-06 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_imageurl_instagramstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='upload_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='upload_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
