# Generated by Django 2.0.2 on 2018-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20180606_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
