# Generated by Django 2.0.2 on 2018-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20180611_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser',
            name='fbpageid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='instagramId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
