# Generated by Django 2.0.3 on 2018-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date acquired')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=35)),
                ('redirect_uri', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
