# Generated by Django 2.0.3 on 2018-03-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcode', '0002_auto_20180309_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthenticationToken',
        ),
        migrations.AddField(
            model_name='instagramclient',
            name='client_secret',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='instagramclient',
            name='client_id',
            field=models.CharField(max_length=50),
        ),
    ]
