# Generated by Django 2.0.3 on 2018-03-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcode', '0003_instagramuser_password'),
        ('authcode', '0005_auto_20180323_1642'),
    ]

    operations = [
    ]
