# Generated by Django 2.0.3 on 2018-03-18 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 18, 16, 22, 8, 538328)),
            preserve_default=False,
        ),
    ]
