# Generated by Django 2.0.3 on 2018-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_image_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
