# Generated by Django 2.0.3 on 2018-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180318_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_story',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
