# Generated by Django 2.0.2 on 2018-04-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_image_is_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
