# Generated by Django 2.0.2 on 2018-03-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_selectedimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedImages',
            new_name='SelectedImage',
        ),
    ]
