# Generated by Django 2.0.2 on 2018-04-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_instagramclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='selectedimage',
            name='instagram_user',
        ),
        migrations.DeleteModel(
            name='InstagramUser',
        ),
        migrations.DeleteModel(
            name='SelectedImage',
        ),
    ]
